
service: theylive

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1
  memorySize: 256

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sdb:*"
      Resource: "*"

functions:
  cron:
    handler: handler.cron
    events:
      - schedule:
        rate: rate(10 minutes)
        input:
          group: oncePer10Mins
      - schedule:
        rate: rate(1 day)
        input:
          group: oncePerDay
