
service: theylive

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sdb:*"
      Resource: "*"

functions:
  cron:
    handler: handler.cron
    events:
      - schedule: rate(10 minutes)
